/* eslint-disable @next/next/no-img-element */
// 'use client'
import React from 'react'
import {Button, Link} from "@nextui-org/react";
import { brawler, chackra, exo, fjalla, rowdies } from "../app/ui/fonts";
import Habilidades from './habilidades/page';
import Experiencia from './experiencia/page';
import Proyectos from './proyectos/page';
import { motion } from "framer-motion"


 export const metadata = {
   title: "Gabriel Mendoza Portfolio",
   description: "Generated by create next app",
 };

const HomePage = () => {
  return (
    <div className='pageGeneral'>
    
      <div className='titleArea'>
        <div className={` textarea`}>
          

      <p className={`${fjalla.className} title1`}>
        Full Stack Developer 
      </p>
      
 
      <p className={`${rowdies.className} title2`}>
        Mid Level en el desarrollo de Software
      </p>
      <p className={`${rowdies.className} title3`}>
        Diseñando soluciones, construyendo éxitos
      </p>
      <Button  color='secondary' className={`${chackra.className} } buton1`} >
        <Link  className='botonPrincipal'
         href='https://www.linkedin.com/in/jesus-gabriel-mendoza-arraiz-2a0838300/overlay/1712281489089/single-media-viewer/?profileId=ACoAAE0CipgBy2OoPgJ9E9ObxrpXrE3zZXVYsMc'>
      Mi Curriculum
      </Link>
      </Button>
      </div>

      <img src='https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExMzZvYXk2dTc3ZWZpdjBhZmRxaGg1a3JhNGx3ZHBvMGw4MTA3eWpmMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qgQUggAC3Pfv687qPC/giphy.gif'
      alt='gif'
      className='gif'/>
      
      </div>

     

    <Habilidades/>

    <Experiencia/>

    <Proyectos/>
      

    </div>
  )
}

export default HomePage